### ISSUE TITLE
Constant name map?

### ISSUE THREAD

**Issue by JoyMonteiro** [mcgibbon/sympl#10]
To cater for different models' requirements in terms of naming constants, would if make sense
to add a constant name map in sympl which can be modified at runtime?

something like a `sympl.set_alias_for_constant`?

**Comment by mcgibbon** [comment]
I'm fairly strongly opposed to using aliases for constants, the way you've done for some of the CliMT objects. So we should discuss your motivations for doing it and get on the same page over Skype sometime. Maybe right now?

**Comment by mcgibbon** [comment]
One of the main benefits of using Sympl for constants is that it is immediately clear when you read a component's code what constants they are using. Having aliases obscures this, makes it easier for users to introduce bugs into their code, and increases cognitive overhead when reading code from multiple component sources.

**Comment by JoyMonteiro** [comment]
Think the chat helped, closing this!
