### ISSUE TITLE
set_constant should ensure units are valid

### ISSUE THREAD

**Issue by mcgibbon** [mcgibbon/sympl#11]
Currently set_constant is only a light wrapper that sets constants in the default_constant dictionary. It would be nice if it also warned users (with an exception) when they give invalid units.

**Comment by JoyMonteiro** [comment]
Such a feature would be only possible if the constant with the given name already exists in the library. I don't see how it could work for arbitrary constants. Is that what you were hoping it does?

**Comment by mcgibbon** [comment]
Makes sure our unit handling library doesn't raise an exception when given those units. That they are actually a unit and not a random string or a typo.

**Comment by JoyMonteiro** [comment]
New PR should address this.

**Comment by mcgibbon** [comment]
Closed by #13
