### ISSUE TITLE
Time tests fail with netcdftime attribute errors

### ISSUE THREAD

**Issue by njweber2** [mcgibbon/sympl#23]
Most tests in `test_time.py` will fail with messages like:
``` AttributeError: module 'netcdftime' has no attribute 'DatetimeNoLeap' ```
because I am using the netcdftime package that comes with netcdf4, which is not the one you want Sympl to use.

**Comment by mcgibbon** [comment]
Thanks :P I'll have to add in some kind of way of checking whether the netcdftime package installed is the correct version, and if not then disabling its functionality.

**Comment by mcgibbon** [comment]
Closed by #26 .
