### ISSUE TITLE
Remove directional wildcards

### ISSUE THREAD

**Issue by mcgibbon** [mcgibbon/sympl#24]
I propose we remove 'x', 'y', and 'z' as wildcards, and instead have only '*' (with the possibility of named wildcards in the future). The basic reason is that there is almost no legitimate use case for these directional wildcards, and in the rare case where they are applicable the same effect can be achieved by passing in the direction name to the component on initialization, which is arguably more clear and obvious to users than the current system.

**No real use case for these**

In the case where components need to know a dimension corresponds to a direction, they almost always also need to know about what the grid is like along that direction (e.g. staggered or colocated). The main example is dynamical cores. In those cases, wildcard dimensions aren't useful. On the opposite end, if a component doesn't need to know about the grid, it generally doesn't care what direction the dimensions correspond to.

The only counter-example I could think of is a component that computes zonal means. However, for those we have the fact that we...

**Can get the same effect without wildcards**

All the component needs to do is accept an arg or kwarg on initialization that gives it the dimension name for the direction it wants, and it pops that dimension name in everywhere in its properties dictionaries where it would normally have a wildcard. This is in fact identical, since we can only have one dimension match for a given direction, so if you know a given dimension name will be present, others cannot be.

Right now a vast amount of the most confusing code in the code base is to handle these directional wildcards, and it could be greatly simplified if we can remove it.

**Comment by JoyMonteiro** [comment]
Just to clarify, the dimension names are also 'x', 'y', 'z'. For instance, in [here](https://github.com/mcgibbon/sympl/blob/de61edac00ec8a132564d2cc496bb51f730d3f9d/sympl/_core/util.py#L20):
dimension names and default labels are both 'x', 'y', 'z'.

if we initialise an additional dimension label for 'x' as (say) 'longitude', and then have an input property for a component whose dims are ['x'], then are you saying it won't match 'longitude'?

I guess what is confusing to me is what is a wildcard and what is not.

**Comment by mcgibbon** [comment]
There would no longer be any registration of dimensions in Sympl. 'x' would only match 'x'. '*' can be used where a wildcard is needed.

**Comment by JoyMonteiro** [comment]
ok. I can see how to refactor climt without requiring major surgery, especially since the next release will completely switch to the *_properties API.

I'm fine with this change, especially if you think it will make the codebase simpler.

**Comment by mcgibbon** [comment]
Closed by #26
