### ISSUE TITLE
Constants string does not get updated when adding new constants

### ISSUE THREAD

**Issue by JoyMonteiro** [mcgibbon/sympl#27]
The get_constants_string provides a printable string of all constants currently registered with sympl. set_constant adds a new constant, but there is currently no logic to add this constant to output of  get_constants_string().

The constant exists, but does not show up when printing, and this could confuse users.

Also, the docstring for reset_constants need to reflect the fact that constant aliases are also reset and the 
condensible is set back to `water'.

**Comment by mcgibbon** [comment]
Thanks! I'll plan to implement these in the in the 0.4.0 release.

**Comment by mcgibbon** [comment]
Closed by #26 .
