### ISSUE TITLE
Rename Diagnostic

### ISSUE THREAD

**Issue by mcgibbon** [mcgibbon/sympl#32]
Some people have brought up and we have also found that it's a little confusing to talk about `Diagnostic`s producing diagnostics, especially when `Prognostic`s produce diagnostics along with every other component. I'm not sure what a better name is, however, and we've been pondering this for some time. It may be that we need to rename multiple components so they all have a similar style of naming.

Some possibilities:

- We could rename multiple components so that we have `DiagnosticScheme`, `PrognosticScheme`, `ImplicitScheme` or similarly for `DiagnosticComponent` etc.
- `Adjustment` is good to describe components that modify existing inputs, but doesn't apply to many diagnostic schemes.
- That's all I've got for now.

**Comment by JoyMonteiro** [comment]
I don't understand what `Scheme` means here. Are you suggesting we extend the base class names by adding suffixes (and create subclasses) or create a large number of new classes?

I think the confusion arises from the fact that there exists no model currently with a set of classes like sympl does. diagnostics are part of the output, and no one cares how they are generated. I'm hesitant to accommodate a change which takes sympl backwards in time to make it correspond well with current model structure/usage.

**Comment by mcgibbon** [comment]
I mean extend the base class names, without creating any subclasses or new classes. Just changing the names of the base classes.

It's confusing to have the word "diagnostic" refer to either a `Diagnostic` component or a diagnostic quantity. This is confusing regardless of the current modeling paradigm.

**Comment by JoyMonteiro** [comment]
In that case, I would prefer adding the `Component` suffix -- makes it very clear what it is.

**Comment by mcgibbon** [comment]
I agree that this appears to be the cleanest option at the moment. I'll do this for 0.4.0 so we can use this language in the paper, along with the Implicit -> Stepper change.

**Comment by mcgibbon** [comment]
Final language change is
Diagnostic --> DiagnosticComponent
Prognostic --> TendencyComponent
Implicit --> Stepper
TimeStepper --> TendencyStepper

Additionally, TimeStepper will be a subclass of Stepper.

**Comment by JoyMonteiro** [comment]
Ack. Close this issue now?

**Comment by mcgibbon** [comment]
I'll close this and several other issues when we merge their pull requests.

**Comment by mcgibbon** [comment]
Fixed by #26
