### ISSUE TITLE
Rename Implicit to (Time)Stepper, TimeStepper to PrognosticStepper

### ISSUE THREAD

**Issue by mcgibbon** [mcgibbon/sympl#34]
I was thinking about how currently the API of TimeStepper is such that it implements Implicit, and that really TimeStepper should be a subclass of Implicit. I propose we do so, and rename the objects to make this make more sense. Implicit could be called Stepper or TimeStepper, and TimeStepper could be called PrognosticStepper (since it steps Prognostic objects).

**Comment by JoyMonteiro** [comment]
Actually, as I was revising the manuscript I realised this exact thing. I think this makes sense, and will remove some of the ambiguity that people encounter when I talk about the class names.

I support Implicit being called Stepper. PrognosticStepper also sounds fine.

**Comment by mcgibbon** [comment]
Fixed while fixing #32
