### ISSUE TITLE
Add support for packing tracers

### ISSUE THREAD

**Issue by mcgibbon** [mcgibbon/sympl#36]
We're adding some support for packing tracer quantities into a single array, for example to be used in GFS in CliMT. Originally I was planning to have tracers inserted in the same way as any other input, but came to the issue that there are valid cases where quantities must be present both as their own separate input and as an entry in the tracer array within `input_properties` (but still not within output property dictionaries). For example, when GFS wraps any `TendencyComponent` that requires moisture as an input, such as RRTMG.

Instead, tracers will not appear in property dictionaries as normal inputs. This information is not actually necessary, since it's contained centrally (accessible via `get_tracer_unit_dict`). Instead, only `uses_tracers` (e.g. `True`), `tracer_dims` (e.g. `['tracer', 'mid_levels', '*']`), and `prepend_tracers` (e.g. `[('specific_humidity', 'kg/kg')]`) attributes will be used to store tracer information on a component.

**Comment by mcgibbon** [comment]
The downside of the above would be that the component does in fact require those tracer quantities as inputs and produce them as outputs, but this wouldn't be shown by the `properties` dictionaries. The user would need to realize this because of the component having `uses_tracers = True` and the tracer being registered. An alternative would be to have a `'tracers'` entry in the properties dictionaries whose value is another property dict with entries for tracers... but this could also be messy.

**Comment by JoyMonteiro** [comment]
Yes, this could cause issues when trying to automate model building. Or maybe it could be an interpretation issue -- Is it sensible to assume that if `uses_tracers=True`, then it is also something that is output if the component is a `Stepper`? I think not. Then, can we use two flags `uses_tracers` and `modifies_tracers` to provide information about whether the tracers could also potentially be modified?

Then, code which automates model building could query the tracer database, and build a list of inputs and outputs which is accurate?

**Comment by JoyMonteiro** [comment]
Yes, it won't cause issues if we can assume that the latter is true. Sounds fine to me!

**Comment by mcgibbon** [comment]
Fixed by #26
