### ISSUE TITLE
Publication with the Journal of Open Research Software?

### ISSUE THREAD

**Issue by DamienIrving** [mcgibbon/sympl#6]
I was wondering if you'd considered publishing the details of sympl with the [Journal of Open Research Software](https://openresearchsoftware.metajnl.com/)? It's a great way to get academic credit for all the hard work involved in releasing and maintaining research software. I'm an Associate Editor with JORS and would love to see a submission on sympl :-)

**Comment by mcgibbon** [comment]
Thank you for the invitation! I'll keep it in mind, perhaps when we've ironed out a couple more kinks. It may or may not make sense to have a separate publication for Sympl, which is purely model infrastructure code, from CliMT, which has physical representation code and might be better placed in a geoscience-focused journal. I'll talk with @JoyMonteiro about this.
